id: sync_from_git
namespace: system

description: |
  Git sync workflow for maintaining flows from repository.
  This workflow runs every 15 minutes to sync flows from the repository.

tasks:
  - id: sync_flows
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/MrBloodrune/kestra-workflows
    branch: main
    # Git authentication using secrets
    username: "{{ secret('GITHUB_USERNAME') }}"
    password: "{{ secret('GITHUB_TOKEN') }}"
    # Target namespace configuration
    targetNamespace: dev
    includeChildNamespaces: true
    # Git directory settings
    gitDirectory: flows

triggers:
  # Schedule trigger for automatic syncing
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
    backfill:
      start: "2024-01-01T00:00:00Z"

  # Optional webhook trigger for manual syncing
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"