id: sync_flows_from_git
namespace: dsn.system

description: |
  Initial Git sync flow that will sync all workflows from repository.
  Note: The dsn and dsn.system namespaces must exist before this flow can run.

tasks:
  - id: check_namespaces
    type: io.kestra.plugin.core.log.Log
    message: "Starting Git sync - ensure dsn and dsn.system namespaces exist"

  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/MrBloodrune/kestra-workflows
    branch: main
    username: git_username
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    targetNamespace: dsn
    includeChildNamespaces: true
    gitDirectory: flows
    delete: true
    dryRun: false

triggers:
  # Run every hour
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"
    
  # Trigger on GitHub webhook
  - id: github_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
