id: hello_world
namespace: dev

tasks:
  - id: first_task
    type: io.kestra.plugin.core.log.Log
    message: Hello from Kestra workflow!

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 */1 * * *"