id: test_trigger
namespace: dsn.operations.noc

description: |
  A simple test workflow to verify our Git sync configuration is working.
  This should be picked up by the sync_flows_from_git flow.

tasks:
  - id: test
    type: io.kestra.plugin.core.log.Log
    message: "Git sync is working! Current time: {{ now() }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"  # Runs every 5 minutes