# Database Configuration
datasources:
  postgres:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximumPoolSize: 30
    minimumIdle: 5
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000

kestra:
  # Repository Configuration
  repository:
    type: postgres
    postgres:
      tables-prefix: kestra_
      migrations: true
      connection-pool:
        max-pool-size: 30
        min-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
  
  # Queue Configuration
  queue:
    type: postgres
    postgres:
      tables-prefix: kestra_
      pollInterval: 500
      retry:
        maxAttempts: 3
        backoffInitialInterval: 1000
        backoffMaxInterval: 10000
  
  # Storage Configuration
  storage:
    type: local
    local:
      basePath: "/app/storage"
  
  # Server Configuration
  server:
    basicAuth:
      enabled: true
      username: ${KESTRA_USERNAME}
      password: ${KESTRA_PASSWORD}
    metrics:
      enabled: true
      prometheus:
        enabled: true
  
  # Task Configuration
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  
  # Plugin Configuration
  plugins:
    repositories:
      central:
        url: https://repo.maven.apache.org/maven2/
    locations:
      - "io.kestra.plugin:plugin-git:LATEST"

  # Variables
  variables:
    db-host: ${DB_HOST}
    db-port: ${DB_PORT}
    db-name: ${DB_NAME}
    db-user: ${DB_USER}
    db-password: ${DB_PASSWORD}
    openai-api-key: ${OPENAI_API_KEY}
    ollama-host: ${OLLAMA_HOST}
    ollama-model: ${OLLAMA_MODEL}

  # Git Integration
  git:
    syncEnabled: true
    url: ${KESTRA_GIT_URL}
    branch: main
    username: ${KESTRA_GIT_USERNAME}
    password: ${KESTRA_GIT_TOKEN}
    pollInterval: PT1M

  # Logging Configuration
  logging:
    level:
      root: INFO
      org.kestra: DEBUG
    console:
      enabled: true
      pattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  # Flow Configuration
  flows:
    directory: "/app/flows"
    persistent: true
    defaultNamespace: "dev"
    storagetype: "postgres"